# Generated by Django 5.0.1 on 2024-03-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_title_task_name_rename_completed_task_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='todo_name',
        ),
    ]
