# Generated by Django 5.0.1 on 2024-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_name_task_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_name',
            field=models.CharField(max_length=255),
        ),
    ]
